parameters:
  api-key:
    default: 0362e681-3ed7-4fad-a927-c2635a273fa2
    description: The name of the environment variable containing your Heroku API Key.
    type: env_var_name
  app-name:
    default: $HEROKU_APP_NAME
    description: >-
      The name of your Heroku App. For backwards compatibility the literal value
      `$HEROKU_APP_NAME` is the default, so you can easily use this command by
      setting an environment variable called HEROKU_APP_NAME
    type: string
  branch:
    default: $CIRCLE_BRANCH
    description: Deploy the given branch. The default value is your current branch.
    type: string
  force:
    default: false
    description: >-
      Whether or not to force the git push (i.e. `git push -f`). Defaults to
      false.
    type: boolean
  maintenance-mode:
    default: false
    description: >-
      Use this to automatically enable mantainance mode before pre-deploy steps
      and have it disabled after post-deploy steps have been run.
    type: boolean
  no_output_timeout:
    default: 10m
    description: >-
      Allows you to specify the no_output_timeout for the `git push` to heroku.
      Defaults to 10m.
    type: string
  tag:
    default: $CIRCLE_TAG
    description: Deploy the given tag. The default value is your current tag.
    type: string
jobs:
  lint-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          command: |
            flake8 .
          name: Lint
      - run:
          command: |
            python test_hello.py
          name: Test
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/check-authentication
      - heroku/deploy-via-git:
          api-key: << parameters.api-key >>
          app-name: << parameters.app-name >>
          branch: << parameters.branch >>
          force: << parameters.force >>
          maintenance-mode: << parameters.maintenance-mode >>
          no_output_timeout: << parameters.no_output_timeout >>
          tag: << parameters.tag >
orbs:
  python: circleci/python@1.4.0
  heroku: circleci/heroku@1.2.6
version: 2.1
workflows:
  main:
    jobs:
      - lint-test
      - deploy:
          requires:
            - lint-test
          filters:
            branches:
              only: main
